name: hourly-cron
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call to update events
        working-directory: /home/runner/work/teamsnap-google-calendar
        run: |
          npm run sync-events
